# Generated by Django 4.2.1 on 2023-07-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
